import { Question } from './types';

export const INITIAL_QUESTIONS: Question[] = [
  // Basic ICT & Tech Concepts
  { id: 1, category: "Basic ICT & Tech Concepts", question: "What is the difference between software and hardware?", options: ["Hardware is physical, software is virtual", "Software is physical, hardware is virtual", "They are the same", "One is for input, one for output"], correctAnswerIndex: 0 },
  { id: 2, category: "Basic ICT & Tech Concepts", question: "What are the functions of RAM and ROM?", options: ["RAM is for long-term storage, ROM for temporary data", "RAM is for temporary data, ROM for boot instructions", "Both are for long-term storage", "Both are for temporary data"], correctAnswerIndex: 1 },
  { id: 3, category: "Basic ICT & Tech Concepts", question: "Name 3 operating systems commonly used in computers.", options: ["Windows, macOS, Linux", "Microsoft Office, Photoshop, Chrome", "Intel, AMD, Nvidia", "HTTP, FTP, SMTP"], correctAnswerIndex: 0 },
  { id: 4, category: "Basic ICT & Tech Concepts", question: "What is the purpose of a router in a network?", options: ["To connect to the internet", "To direct traffic between networks", "To store files", "To provide power to devices"], correctAnswerIndex: 1 },
  { id: 5, category: "Basic ICT & Tech Concepts", question: "What is cloud computing?", options: ["Storing data on your personal computer", "Using a network of remote servers to store and manage data", "A type of weather forecasting technology", "A new type of laptop"], correctAnswerIndex: 1 },

  // Practical IT Knowledge
  { id: 6, category: "Practical IT Knowledge", question: "How would you solve a computer that won’t boot?", options: ["Hit it", "Check power connections and hardware", "Buy a new one", "Install more RAM"], correctAnswerIndex: 1 },
  { id: 7, category: "Practical IT Knowledge", question: "A printer is not responding — what would you do?", options: ["Restart the printer and check connections", "Throw it away", "Print again multiple times", "Update the computer's OS"], correctAnswerIndex: 0 },
  { id: 8, category: "Practical IT Knowledge", question: "What is a firewall and why is it important?", options: ["A physical barrier against fire", "A software that helps cool the PC", "A network security system that monitors traffic", "A tool for faster internet"], correctAnswerIndex: 2 },
  { id: 9, category: "Practical IT Knowledge", question: "How do you clean malware from a system?", options: ["Delete random files", "Run antivirus and anti-malware scans", "Format the hard drive without backup", "Unplug the computer"], correctAnswerIndex: 1 },
  
  // Company & Workplace Behavior
  { id: 10, category: "Company & Workplace Behavior", question: "How do you handle conflict with coworkers?", options: ["Ignore them", "Discuss the issue privately and respectfully", "Complain to everyone else", "Quit the job"], correctAnswerIndex: 1 },
  { id: 11, category: "Company & Workplace Behavior", question: "How do you organize your daily work tasks?", options: ["Remember them all", "Use a to-do list or task manager", "Do whatever feels most urgent", "Wait for instructions for each task"], correctAnswerIndex: 1 },
  { id: 12, category: "Company & Workplace Behavior", question: "Describe a time when you had to learn something new quickly.", options: ["This is an open-ended question for discussion", "I have never had to do this", "I avoid learning new things", "I ask others to do it for me"], correctAnswerIndex: 0 },

  // Training and Development
  { id: 13, category: "Training and Development", question: "How do you stay updated with new technology trends?", options: ["I don't", "By reading tech blogs, news, and attending webinars", "Wait for my company to train me", "Only use old, stable technology"], correctAnswerIndex: 1 },
  { id: 14, category: "Training and Development", question: "What technical certifications do you have (e.g. Cisco, CompTIA)?", options: ["This is for applicant to answer", "None", "I have a library card", "I have a driver's license"], correctAnswerIndex: 0 },

  // Device & Technical Troubleshooting
  { id: 15, category: "Device & Technical Troubleshooting", question: "What steps would you take to fix a slow computer?", options: ["Buy a new one immediately", "Check for malware, close background apps, free up disk space", "Restart it 10 times", "Hit the monitor"], correctAnswerIndex: 1 },
  { id: 16, category: "Device & Technical Troubleshooting", question: "What causes overheating in a laptop?", options: ["Using it too much", "Dust blocking vents, and failing fans", "Bright screen settings", "Loud volume"], correctAnswerIndex: 1 },
  { id: 17, category: "Device & Technical Troubleshooting", question: "How can you protect a system against power surges?", options: ["Use a surge protector or UPS", "Unplug it during a storm", "Keep it on a wooden table", "Both A and B are correct"], correctAnswerIndex: 3 },
  
  // Internet and Network Knowledge
  { id: 18, category: "Internet and Network Knowledge", question: "What is an IP address?", options: ["A physical location for a computer", "A unique address that identifies a device on a network", "A type of computer processor", "A brand of internet service provider"], correctAnswerIndex: 1 },
  { id: 19, category: "Internet and Network Knowledge", question: "Explain the difference between WiFi and mobile data.", options: ["No difference", "WiFi uses a router, mobile data uses a cell tower", "WiFi is faster", "Mobile data is free"], correctAnswerIndex: 1 },
  { id: 20, category: "Internet and Network Knowledge", question: "What does VPN stand for and what is its use?", options: ["Very Productive Network; for office work", "Virtual Private Network; for secure connections", "Virtual Public Network; for public access", "Very Personal Notebook; a type of laptop"], correctAnswerIndex: 1 },
  { id: 21, category: "Internet and Network Knowledge", question: "What is the function of DNS?", options: ["To speed up downloads", "To block viruses", "To translate domain names to IP addresses", "To manage computer hardware"], correctAnswerIndex: 2 }
];

export const QUIZ_LENGTH = 10;
export const MAX_ATTEMPTS = 3;
export const QUIZ_TIME_SECONDS = 10 * 60; // 10 minutes

export const translations: Record<string, Record<string, string>> = {
  en: {
    welcome: "Welcome to TechHire Hub",
    welcome_desc: "The modern platform for assessing tech talent. Press the button below to begin your assessment.",
    start_assessment: "Start Assessment",
    register: "Applicant Registration",
    name: "Full Name",
    contact: "Email or Phone Number",
    position: "Position Applied For",
    start_quiz: "Start Quiz",
    quiz_title: "Tech Assessment Quiz",
    time_left: "Time Left",
    submit: "Submit",
    results_title: "Quiz Results",
    score: "Your Score",
    feedback: "Feedback",
    congrats_message: "Congratulations! You're shortlisted for the job.",
    interview_offer: "You've done great! Proceed to the interview.",
    retake_message: "You may retake the quiz to improve your chances.",
    sorry_message: "Sorry, please review your knowledge and try again later.",
    your_answer: "Your Answer",
    correct_answer: "Correct Answer",
    retake_quiz: "Retake Quiz",
    no_more_attempts: "You have used all your attempts.",
    export_pdf: "Export to PDF",
    email_results: "Email Results",
    email_subject: "My TechHire Hub Quiz Results",
    email_body: "Here are my results from the TechHire Hub assessment.",
    admin_panel: "Admin Panel",
    add_question: "Add Question",
    question_text: "Question Text",
    option: "Option",
    correct: "Correct",
    category: "Category",
    save: "Save",
    delete: "Delete",
    edit: "Edit",
    cancel: "Cancel",
    admin_login: "Admin Access",
    go_back: "Go Back",
    question: "Question",
    of: "of",
    next: "Next",
    previous: "Previous",
    start_interview: "Start Interview",
    interview_title: "Screening Interview",
    type_message: "Type your message...",
    send: "Send",
    interview_complete: "Interview Complete",
    finish_interview: "Finish & View Results",
    interview_transcript: "Interview Transcript",
  },
  fr: {
    welcome: "Bienvenue sur TechHire Hub",
    welcome_desc: "La plateforme moderne pour évaluer les talents tech. Cliquez sur le bouton ci-dessous pour commencer votre évaluation.",
    start_assessment: "Commencer l'évaluation",
    register: "Inscription du Candidat",
    name: "Nom Complet",
    contact: "Email ou Numéro de Téléphone",
    position: "Poste Postulé",
    start_quiz: "Commencer le Quiz",
    quiz_title: "Quiz d'Évaluation Technique",
    time_left: "Temps Restant",
    submit: "Soumettre",
    results_title: "Résultats du Quiz",
    score: "Votre Score",
    feedback: "Commentaires",
    congrats_message: "Félicitations ! Vous êtes présélectionné pour le poste.",
    interview_offer: "Excellent travail ! Passez à l'entretien.",
    retake_message: "Vous pouvez refaire le quiz pour améliorer vos chances.",
    sorry_message: "Désolé, veuillez revoir vos connaissances et réessayer plus tard.",
    your_answer: "Votre Réponse",
    correct_answer: "Bonne Réponse",
    retake_quiz: "Refaire le Quiz",
    no_more_attempts: "Vous avez utilisé toutes vos tentatives.",
    export_pdf: "Exporter en PDF",
    email_results: "Envoyer les Résultats par Email",
    email_subject: "Mes résultats du quiz TechHire Hub",
    email_body: "Voici mes résultats de l'évaluation TechHire Hub.",
    admin_panel: "Panneau d'Administration",
    add_question: "Ajouter une Question",
    question_text: "Texte de la Question",
    option: "Option",
    correct: "Correct",
    category: "Catégorie",
    save: "Enregistrer",
    delete: "Supprimer",
    edit: "Modifier",
    cancel: "Annuler",
    admin_login: "Accès Admin",
    go_back: "Retour",
    question: "Question",
    of: "de",
    next: "Suivant",
    previous: "Précédent",
    start_interview: "Commencer l'Entretien",
    interview_title: "Entretien de Présélection",
    type_message: "Écrivez votre message...",
    send: "Envoyer",
    interview_complete: "Entretien Terminé",
    finish_interview: "Terminer et Voir les Résultats",
    interview_transcript: "Transcription de l'Entretien",
  },
  rw: {
    welcome: "Murakaza neza kuri TechHire Hub",
    welcome_desc: "Urubuga rugezweho rwo gusuzuma impano mu ikoranabuhanga. Kanda buto iri hasi kugirango utangire isuzuma.",
    start_assessment: "Tangira Isuzuma",
    register: "Kwiyandikisha k'umukandida",
    name: "Amazina Yuzuye",
    contact: "Email cyangwa Nimero ya Telefone",
    position: "Umwanya Wasabye",
    start_quiz: "Tangira Ikizamini",
    quiz_title: "Ikizamini cy'Ubumenyi mu Ikoranabuhanga",
    time_left: "Igihe Gisigaye",
    submit: "Emeza",
    results_title: "Ibisubizo by'Ikizamini",
    score: "Amanota Yawe",
    feedback: "Ibitecyerezo",
    congrats_message: "Shimwa! Washyizwe ku rutonde rw'abakomeza.",
    interview_offer: "Wakoze neza cyane! Komeza ku kabazo.",
    retake_message: "Ushobora kongera gukora ikizamini kugirango wongere amahirwe yawe.",
    sorry_message: "Bambi, ongera usubiremo ubumenyi bwawe uzagerageze bundi.",
    your_answer: "Igisubizo Cyawe",
    correct_answer: "Igisubizo Cy'ukuri",
    retake_quiz: "Subiramo Ikizamini",
    no_more_attempts: "Wakoresheje amahirwe yawe yose.",
    export_pdf: "Bika nka PDF",
    email_results: "Ohereza Ibisubizo kuri Email",
    email_subject: "Ibisubizo byanjye bya TechHire Hub",
    email_body: "Ngibyo ibisubizo byanjye by'isuzuma rya TechHire Hub.",
    admin_panel: "Imicungire y'ibibazo",
    add_question: "Ongeramo Ikibazo",
    question_text: "Ikibazo",
    option: "Ihisemo",
    correct: "Cy'ukuri",
    category: "Icyiciro",
    save: "Bika",
    delete: "Siba",
    edit: "Hindura",
    cancel: "Rekura",
    admin_login: "Kwinjira nk'umuyobozi",
    go_back: "Subira Inyuma",
    question: "Ikibazo",
    of: "cya",
    next: "Komeza",
    previous: "Banza",
    start_interview: "Tangira Ikibazo",
    interview_title: "Ikibazo cy'Ijonjora",
    type_message: "Andika ubutumwa bwawe...",
    send: "Ohereza",
    interview_complete: "Ikibazo Kirarangiye",
    finish_interview: "RANGIZA & REBA IBISUBIZO",
    interview_transcript: "Inyandiko y'Ikibazo",
  }
};